import org.junit.Test;

import protocol.HttpResponse;
import protocol.Protocol;

import static org.junit.Assert.*;

import java.io.File;

import org.junit.After;
import org.junit.Before;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jony' at '1/19/17 7:11 PM' with Gradle 2.13
 *
 * @author jony, @date 1/19/17 7:11 PM
 */
public class LibraryTest {
	HttpResponse response;
	private File file;
	
	@Before
	public void setUp() throws Exception {
		file = new File("/EAGM/README");
	}
	
	@After
	public void tearDown() throws Exception {
		
	}

    
    @Test public void testCreateResponse(){
    }
}
